packages:
  - apps/*
  - packages/*
  - "!apps/api"
  - "!services"

catalog:
  axios: 1.13.2
  "@react-router/node": 7.12.0
  "@react-router/serve": 7.12.0
  "isbot": 5.1.31
  "react": 19.2.3
  "react-dom": 19.2.3
  "react-router": 7.12.0
  "@react-router/dev": 7.12.0
  "@tailwindcss/vite": 4.1.13
  "@types/node": "22"
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "tailwindcss": 4.1.13
  "postcss": "8.5.3"
  "typescript": 5.9.2
  "vite": 7.3.1
  "vite-tsconfig-paths": 6.0.4
  "vite-plugin-devtools-json": 1.0.0
  "@tailwindcss/postcss": 4.1.13
  "@dotenvx/dotenvx": 1.49.1
  "tsdown": 0.20.0-beta.3
  "@heroicons/react": 2.2.0
  "react-hook-form": 7.54.2
  "zod": 3.24.1
  "@hookform/resolvers": 3.9.1
  "react-hot-toast": 2.4.1

onlyBuiltDependencies:
  - turbo
